---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsFor": ["state"] }]
